### ISSUE TITLE
iOS linker error

### ISSUE THREAD

**Issue by oziphantom** [igagis/papki#4]
I'm getting 
```
Undefined symbols for architecture armv7:
  "vtable for papki::FSFile", referenced from: papki::FSFile::FSFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in ConvertImagesScene.o
      papki::FSFile::~FSFile() in ConvertImagesScene.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "vtable for papki::File", referenced from:
      papki::File::File(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in ConvertImagesScene.o
      papki::File::~File() in ConvertImagesScene.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
  "svgren::render(svgdom::SvgElement const&, svgren::Parameters const&)", referenced from:
      ConvertImageScene::init() in ConvertImagesScene.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
 Xcode 10 building for iOS the invoking code is
```
std::unique_ptr<svgdom::SvgElement> dom;
        try
        {
            papki::FSFile pfile(svgFile);
            dom = svgdom::load(pfile);
        }
``` 
however the papki lib compiles without any warnings. Maybe it because a lot of the functions don't have anything in the #ifdef platforms for iOS and the compiler/linker is optimising the functions away on iOS?

**Comment by igagis** [comment]
Ok, I see you are trying to build **svgren** on iOS.
Did you use `cocoapods` to install the library to your xcode project? Or did you just add all of the sources to your project?

**Comment by oziphantom** [comment]
cocoapods

svgren seems to compile fine, its only when I actually try and load a file to give to it does it complain.

**Comment by igagis** [comment]
in your project `Build Settings` could you check what are the `Architectures` and `Valid architectures` listed?

**Comment by oziphantom** [comment]
my main app is 
Architectures : Standard
Valid architectures : arm64 arm7
Each of your projects.. svgdom, cairo, svgren, inokod etc 
Architectures : Standard
Valid architectures : arm64 arm7 arm7s

I'm building for a testing on an iPad3 which should be using arm64

**Comment by igagis** [comment]
I cannot reproduce the problem. Could you try the accepted solution from here:
https://stackoverflow.com/questions/37619389/undefined-symbols-for-architecture-armv7-cocoapods-iphone-5

**Comment by oziphantom** [comment]
clean folder - no change
switched to frameworks as per the last post - it then seems that frameworks could not see files from other frameworks so all the include <somethingelse.h> generated files not found errors. So worse ;)

switching back I noticed this in the pod output
```
[!] The `<redacted>-mobile [Debug]` target overrides the `GCC_PREPROCESSOR_DEFINITIONS` build setting defined in `Pods/Target Support Files/Pods-<redacted>-mobile/Pods-<redacted>-mobile.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `<redacted>-mobile [Debug]` target overrides the `LIBRARY_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-<redacted>/Pods-<redacted>-mobile.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `com.symbolicone.ouille-mobile [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-<redacted>-mobile/Pods-<redacted>-mobile.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `<redacted>-mobile [Release]` target overrides the `GCC_PREPROCESSOR_DEFINITIONS` build setting defined in `Pods/Target Support Files/Pods-<redacted>-mobile/Pods-<redacted>-mobile.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `<redacted>-mobile [Release]` target overrides the `LIBRARY_SEARCH_PATHS` build setting defined in `Pods/Target Support Files/Pods-<redacted>-mobile/Pods-<redacted>-mobile.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `<redacted>-mobile [Release]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods-<redacted>/Pods-<redacted>.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

So this might be a case of cocos2d-x and pods fighting with each other... I'm an MSVC guy so clangs terms mean nothing to me ;)

**Comment by igagis** [comment]
dod you use `cocos2d-x` in your project? I'm not familiar with `cocos2d-x`, is it installed via `cocoapods` as well? Does it modify the xcode project somehow automatically, as `cocoapods` does?

I'm also not expert in xCode and iOS, so I have a little idea of what these `pod` output mean.

**Comment by oziphantom** [comment]
its a cocos2d-x project, and no its not a pod, its a whole new seperate beast, downloads and sets stuff up with a custom python script etc. Pods makes a "workspace" so I guess the workspace sets up a bunch of settings for these values, then cocos2d-x needs its own values but since one is in the workspace and one is in the project the might overrule the other. I've tried following their `$(inherited)` advice, will see what happens.

**Comment by oziphantom** [comment]
that gets me a similar error but now cocos2d-x can't find symbols for something it wants...  So that seems to be the issue or something based upon it..., its 3am so I will pour some tea, done a white and blue dress and talk to a cat as I tumble down the rabbit hole tomorrow. Thanks for your help.

**Comment by oziphantom** [comment]
For those that come after
deintergate the POD
then add the $(inherit) to your project
update the POD
clean build folder
build
You might now get errors of missing symbols or missing VFPTable errors. This is because the POD will set the `-Obj-C` flag on the linker and for some reason this will cause you to need more frameworks linked in. So find the function is can't find, web search it, find the frame work, add it to your project, build, rinse and repeat.

**Comment by igagis** [comment]
Good to know you finally solved it!
